### ISSUE TITLE
Stage scroll bars appear briefly in windows browsers when stage appears

### ISSUE THREAD

**Issue by gshin02** [wordplaydev/wordplay#200]
## Expected behavior

The code space section shouldn't glitch or try to resize itself.

## Actual behavior

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

The code section keeps trying to resize itself/glitch.

1. Go to the Learn page on a widows device.
2. Resize the window (sometimes it will happen even if you don't resize the window).
3. See error.

## Screenshots

![ezgif-3-10bd38163a](https://github.com/wordplaydev/wordplay/assets/102693117/2f8505bc-6c17-4937-86d1-28179e726446)

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not.

Desktop

-   OS: Windows
-   Browser: chrome, microsoft edge (other browsers too?)

**Comment by amyjko** [comment]
One clarification not clear from the gif: is this happening in a loop, or just once? (I tested on Windows 10/Chrome 117, and it was just happening once on each step forward).

**Comment by gshin02** [comment]
It seems to be happening in a loop on my end.

**Comment by amyjko** [comment]
Fixed! Here was the cause, for those curious:

* The project view has a "canvas" that can optionally be an infinite space of moveable and resizeable windows 
* To make that space scrollable, the canvas div was set to `overflow:auto`
* When in full screen mode, and on an OS like Windows where scroll bar gutters take up space, this led to the canvas being resized to make room for them
* When resized, the canvas responds by performing another layout, adjusting to the smaller canvas size, and removing the need for the scrollbars
* This caused another resize, and therefore an infinite loop of scroll bars appearing and reappearing

The fix was to only scroll the canvas when in free mode, so that the canvas size is infinite rather than fixed to the window.
