### ISSUE TITLE
Firefox - Archived project page cannot show performance and no return button

### ISSUE THREAD

**Issue by KaidiKelsey** [wordplaydev/wordplay#201]
## Expected behavior

When I archive the performance and then click the performance under the Archived projects, it showed an arrow but not the cat it should be. And I cannot return to the previous page. 

## Actual behavior

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

1. Go to 'Project'
2. Click on one of the projects under 'Archived' (the image is cat)
3. See error (it should be cat, but only arrow)
4. I can't return back.

## Screenshots
<img width="1323" alt="Screen Shot 2023-10-13 at 4 50 05 PM" src="https://github.com/wordplaydev/wordplay/assets/97130417/89bbddd7-8acb-4471-842b-f7160c04053c">

<img width="1326" alt="Screen Shot 2023-10-13 at 4 50 13 PM" src="https://github.com/wordplaydev/wordplay/assets/97130417/e3f1524a-f355-4b84-b3b1-da30e765e4c2">

## Environment

browser: FireFox 118.0.2
laptop: macbook

**Comment by amyjko** [comment]
Here's the cause of this issue:

* When a `ProjectPreview` is selected, the `ProjectView` that is shown is supposed to `OutputView` tile and no other tiles, and the project footer toolbar will not be shown since it's in "play" mode.
* However, if the output view was previously minimized (with the x button in the top right of the tile), when the project is shown, no tiles will be visible, and since there is no project footer to expand the `OutputView` again, there's no way to escape

There are a few things we need to do to prevent this from happening:

* When entering "play" mode in a project view, ensure that the `OutputView` tile is shown, even if it was previously minimized, since play mode is explicitly requesting to see the output
* There needs to be some way of leaving play mode from the `OutputView` tile, other than navigating back in the browser, since the project footer is hidden.
* The 'x' button is likely miscommunicating its purpose; the report above suggests that its being seen as a "close project" button, when it's actually a "minimize tile" button. We should be using a macOS and Windows convention of "-" or "_" instead of "x" to more clearly communicate it's purpose.

**Comment by amyjko** [comment]
* Replaced minimize label with '–'
* Ensured that full screen tile is expanded
