### ISSUE TITLE
Fix the exit button on gallery projects 

### ISSUE THREAD

**Issue by soniadashti** [wordplaydev/wordplay#205]
## Expected behavior
After selecting a gallery project and clicking the exit button on the top right corner, you should be taken back to the gallery. 

## Actual behavior
Steps to find the issue:
1. Select any project in the gallery
2. Attempt to click the “-” on the top right corner  

You will notice that you cannot click the exit button 

## Environment
Safari on MacOS Version 12.6 (21G115)

**Comment by amyjko** [comment]
The `-` button on the top right is not an exit button, it's a minimize button, and it's disabled while in play mode. The only exit button is the browser back button or the home button. So this isn't a defect, but a design issue, since the `-` button is being interpreted as an "exit".

What would clarify this? The tooltip says "collapse window", which may be confusing. Perhaps the symbol used is confusing? What would better communicate minimize and not communicate "exit", since that's not what it does?

Additionally, what would be a better way of communicating that the way to return to the gallery is the back button or the gallery link at the bottom?

**Comment by amyjko** [comment]
@soniadashti, can you chime in on the design considerations above?

**Comment by soniadashti** [comment]
@amyjko This was confusing for myself and some others because we had assumed there would be a way to exit out of the specific performance and return back to the galleries. I typically see the exit button options in the farthest corner so this was a false assumption on my part. 

If it is for minimizing, the symbol is a great option. Since it may be confusing for users to first grasp why the button won't click when in play mode, I would not include the minimize symbol when it is not clickable. When looking at my Safari, if I am in full screen the middle minimize icon turns into a blank grey circle, making it clear this is not currently an option for me to click on. Once I leave full screen, the minimize icon reappears and now I am aware it can click. Clicking it will teach me what it does and also prevent confusion. 

When it comes to communicating how to get back to the gallery, it may be difficult to make it clear for users without verbally saying it. The hope is that after realizing there is not an exit button people will naturally will hit the back button or gallery link.

**Comment by amyjko** [comment]
I implemented a redesign of this:

* Hiding the minimize button in full screen play mode
* Showing the main source file when leaving play mode
* Fixing a bug that hid the "show source" button in play mode
