### ISSUE TITLE
Creating projects using Chinese Characters

### ISSUE THREAD

**Issue by lucylin8** [wordplaydev/wordplay#221]
## Expected behavior

When I am typing in Chinese characters, it doesn't render the English characters into Chinese characters.

## Actual behavior

Go to any page with a coding environment. when you switch to Chinese characters, and then press the Chinese character using a number on the keyboard, it'll show the English characters but not the Chinese character. This appears both in the test website and my local website. 

## Screenshots
<img width="960" alt="Screenshot 2023-10-24 175243" src="https://github.com/wordplaydev/wordplay/assets/91906434/66b597ca-4d62-47b2-a89c-fa23ee7cc285">

<img width="1024" alt="Screenshot 2023-10-24 175056" src="https://github.com/wordplaydev/wordplay/assets/91906434/6ac27594-fccd-4424-9ed7-a4063638272d">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not. Don't skip these; cross-browser issues are a common cause of problems.

Desktop
HP Laptop PC 14-dq2035cl
Chrome 118

**Comment by amyjko** [comment]
Can you update with exact reproduction steps? Anyone fixing this needs to be able to recreate the exact environment you're using, including:

- Exact operating system and version
- Exact browser
- Exact OS keyboard settings and exact keystrokes to reproduce the problem (e.g., precisely define "switch to Chinese characters", specifying what operating system settings you needed to set in order to enable switching.

Edit the description to include these, and then whoever fixes this will be able to reproduce the problem and confirm that they've fixed it. Thanks!

**Comment by amyjko** [comment]
@lucylin8 It would be great to get your reply on this ASAP, we only have a few days left to fix this bug before launch.

**Comment by lucylin8** [comment]
Apologies for the late reply! 

Exact operating system and version: Windows 11, Version 22H2 (OS Build 22621.2428) 

Exact browser: Google Chrome, Chrome 118, Windows 10

Exact OS keyboard settings and exact keystrokes to reproduce the problem (e.g., precisely define "switch to Chinese characters", specifying what operating system settings you need to set to enable switching.

Chinese(Simplified, China), Microsoft Pingyin. I usually use the English keyboard, I change my keyboard setting in Windows by using the windows + space bar(under the same OS, but should be available in most Windows OS). In the Chinese keyboard, you press the keyboard characters to form words, and based on the letters you pressed, the Chinese keyboard will provide Chinese characters formed, and you select them by pressing the option number. However, once I press a number to select my Chinese character, it just turns into English characters. The only way I'm able to use Chinese characters is by manually typing it into another document, and then copy-pasting it to Wordplay.

**Comment by amyjko** [comment]
Thanks! This should suffice for reproduction.

**Comment by amyjko** [comment]
Hi @lucylin8! I think I resolved this; I can't tell entirely since there are so many different ways to set up Chinese input. Play with the fix I just pushed to main and see if it works okay for you?

**Comment by lucylin8** [comment]
It works great now, thanks for fixing it so quickly!!

**Comment by amyjko** [comment]
I'm glad it turned out to be an easy fix. There were 6 different behaviors across Chrome, Firefox, Safari, mac OS, and Windows, but a small number of fixes accounted for all of them. (At least for pinyin input — not sure about the many other forms. I'd love if you did some testing on other input methods!)

**Comment by lucylin8** [comment]
Okay, I'll try out japanese / spanish, are there any specific input methods
you want me to try? I can test out the macos system later today!

**Comment by amyjko** [comment]
Basically anything we haven't tried, including other languages and other input methods. Report any issues you find as new issues.
