### ISSUE TITLE
Password verification for password change and account deletion

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#303]
## What's the problem?

For features like deleting account and change password, it would be great to have the user enter the original password. As a user, i don't feel safe enough if someone can easily change my password or delete my account.

## What's the design idea?

An idea would be to add a password verification process before the user can access to change password or delete account.

## Who benefits?

Almost every user will be benefit from this feature since it enhanced security for users. Others won't be able to change users' password or delete their account. However, this feature might increase the complexity of use.

## Design specification

Not yet.

**Comment by amyjko** [comment]
Thanks @Marc0Guo! One clarification: this would not enhance security in a direct way (since it requires someone having a token nearly impossible to generate and decrypt), but it would enhance security if someone left their laptop unlocked where someone could access it. That scenario seems like a reasonable justification for requiring re-authentication.

There are some design choices to make here. For example, the reauthentication paths would have to be different for username/password accounts versus email only authentication. The former would just require the password, the latter would require re-sending an email login, or a login code of some kind.

**Comment by Marc0Guo** [comment]
Yes, that's the scenario I'm trying to say.

**Comment by amyjko** [comment]
Thanks for the clarification! Can you edit the description of this report to make that clear, for whoever designs for it?
