### ISSUE TITLE
Password recovery for username accounts

### ISSUE THREAD

**Issue by willGG11** [wordplaydev/wordplay#305]
## What's the problem?

Creators with username and password accounts can easily forget their passwords, and since we have no way of contacting them, there is no way for a creator to prove they own an account, making authentication impossible.

The key constraints on this problem are:

* Secret question approaches are inherently insecure, because they are so easily guessable based on other information about a creator.
* [COPPA](https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312) places strict constraints on our ability to gather email addresses or other contact information without parental permission, which is extremely difficult to get. And schools are very risk averse to adopt educational technologies that gather such information.

## What's the design idea?

There is one exception in COPPA that could allow us to use email to do password recovery. One design pattern is described here in non-binding FTC guidance:

[COPPA Exceptions](https://www.ftc.gov/business-guidance/resources/complying-coppa-frequently-asked-questions#J.%20Exceptions%20to%20Prior%20Parental%20Consent)

## Who benefits?

All creators who do not use password managers to track their usernames and passwords, despite the advice on the account creation form.

## Design specification

The general design pattern would be:

* When creators create an account, ask for an email address, explaining that it will not be stored and will only be used this one time to allow login.
* Use the email address to send a sign in link.
* Rather than storing the email address, store a hash of the address, to prevent recovery of the email address and resending of future emails to the address.
* If a user forgets their password, ask for both either a username and email address, and explain that if a matching account is found, an email will be sent. If an account with that username exists with a matching hashed email, mark the password as forgotten, and send a sign in link to the email address. If such a username does not exist with a matching hash, do nothing, to prevent attackers from knowing that such an account does not exist.
* Once the user receives the email, check the password forgotten state, and if it's on (which it should be), prompt the user to change their password. Once changed, set the forgotten state to off.
* Add a feature to change the email address on the account, which sends a sign in email to the new address and updates the email hash.
* Update the privacy policy to mirror the message that email addresses are not stored and are only used for forgotten passwords.

This pattern does not store the email address and uses the COPPA "one-time use" exception to avoid needing to ask for parental consent.

The major downside is that it's very hard to implement, in general, and with Firebase.

**Comment by amyjko** [comment]
Thanks @willGG11! This is not possible because of COPPA (US Federal Law), which requires that we cannot gather personally identifiable information such as email addresses with permission of their parent or guardian. This is the only reason we have a username and password option, for users under 13 using the platform in schools. Some platforms interpret the law differently and gather email address anyway (e.g., Scratch), but not all schools follow this interpretation, which creates a barrier to using the platform in school.

(And, of course, email accounts don't require recovery, since there is no password for them, it's just a magic link each time they log in).

The only real design alternative I see for this is to allow an optional email in username and account creation, with a huge warning for under 13 year olds that they should not provide it. But we would still be legally liable if they did provide it (and many would). I'm not sure that's a risk we can take right now.

If you see another way around this legal constraint (other than just interpreting the law differently), do let me know.

**Comment by willGG11** [comment]
> Thanks @willGG11! This is not possible because of COPPA (US Federal Law), which requires that we cannot gather personally identifiable information such as email addresses with permission of their parent or guardian. This is the only reason we have a username and password option, for users under 13 using the platform in schools. Some platforms interpret the law differently and gather email address anyway (e.g., Scratch), but not all schools follow this interpretation, which creates a barrier to using the platform in school.
> 
> (And, of course, email accounts don't require recovery, since there is no password for them, it's just a magic link each time they log in).
> 
> The only real design alternative I see for this is to allow an optional email in username and account creation, with a huge warning for under 13 year olds that they should not provide it. But we would still be legally liable if they did provide it (and many would). I'm not sure that's a risk we can take right now.
> 
> If you see another way around this legal constraint (other than just interpreting the law differently), do let me know.

I see,  so security questions like name of the city, pet's name, parent's last name are considered as personally identifiable information here, right?

**Comment by amyjko** [comment]
@willGG11 They are, and while they would help with recovery, they're also well known to greatly reduce security, since they're so easily guessable from other information about a person:

* https://www.beyondtrust.com/blog/entry/reused-security-questions-can-pose-a-high-risk-learn-tips-tricks-to-mitigate-the-threat
* https://www.dashlane.com/blog/7-reasons-why-password-recovery-questions-are-worse-than-useless

**Comment by amyjko** [comment]
@willGG11 I did some research and found one possible COPPA workaround that the FTC suggests is compliant (though its a design pattern from staff, and not binding in law, so could still leave the project open to fines of ~$50K per user).

**Comment by amyjko** [comment]
Alas, I think I'm going to have to close this issue. I spent the whole day trying to make this pattern work with Firebase, and it's just not possible without building an entire custom authentication stack, and even then, there are numerous vulnerabilities it exposes. COPPA :(
