### ISSUE TITLE
Tools Gallery calculator 

### ISSUE THREAD

**Issue by lilyforsythe** [wordplaydev/wordplay#356]
## What's the problem?

There are not enough examples in the tools category. 
## What's the design idea?

Our idea is to create a calculator.
## Who benefits?

People who need to calculate or do any math benefit because our program will make it easier for them.
## Design specification

(This section should be included after a design proposal is ready and approved, and the `buildable` tag is added. This text can remain until then. Designers should add their proposal here, not in a comment).

**Comment by lilyforsythe** [comment]
@amyjko Please take a look!

**Comment by amyjko** [comment]
Thanks for documenting this work! I'm excited to see with what you come up with. There's no design spec yet, so I'm keeping the "needs design" tag on this.

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by vTempo** [comment]
Project is completed (for now) waiting for approval and review to be merged into main (from branch calculator).

**Comment by amyjko** [comment]
Thanks @vTempo! I should be able to get to PRs soon. (Some travel, so I'm delayed).
