### ISSUE TITLE
"Gallery Doesn't Exist or Isn't Public" Error when you try to create a new gallery

### ISSUE THREAD

**Issue by soniadashti** [wordplaydev/wordplay#382]
## Expected behavior

When you go to the "Projects" section on the Wordplay website and you attempt to click the "+" you would expect to now be taken to where you can finish creating the gallery that you just attempted to start.

## Actual behavior

1. Go to "Projects" 
2. Click on the "+" below Galleries
3. See error (Refer to Screenshot Below)
4. Go back to "Projects"
5. You will see a new gallery created despite there being an error previously

## Screenshots

<img width="1416" alt="Screen Shot 2024-02-12 at 11 47 33 AM" src="https://github.com/wordplaydev/wordplay/assets/97253346/decdc783-a7f9-4e7b-8ac7-99d6b0449ba9">

## Environment

Macbook Air M1, 2020:

-   macOS Monterey Version 12.6
-   Safari 16.4.1

**Comment by amyjko** [comment]
Thanks for reporting @soniadashti! I'll investigate and fix, unless you'd like to.

**Comment by amyjko** [comment]
@soniadashti I'm unable to reproduce this in Safari or other browsers, or locally in the emulator. Can you? Is there a step possibly missing in your reproduction steps?

**Comment by soniadashti** [comment]
Hi Amy,

I screenrecorded the process to the error for you! 

https://github.com/wordplaydev/wordplay/assets/97253346/be9685cc-07b9-4889-89ee-072d8d2cd3fa

**Comment by amyjko** [comment]
Ah, thanks. The reproduction steps are right, but the issue is intermittent, sometimes happening, sometimes not. It looks like it's due to lag in the gallery being created, where the redirect to the gallery page sometimes happens before the gallery is done being created, and so it shows the error (even though the gallery is created shortly after). I'll investigate further and fix.
