### ISSUE TITLE
Translation in the simplified Chinese instruction is not native or fluent enough.

### ISSUE THREAD

**Issue by Siqi1234** [wordplaydev/wordplay#384]
## Expected behavior

Some translated phrases in the simplified Chinese tutorial are not contextually aware or native, which may be difficult for those who only speak Chinese to comprehend. 

## Actual behavior

1. Go to the simplified Chinese tutorial
2. Read every sentence from beginning
3. Find sentences that are not translated fluently or natively in Chinese. For example, in line 47, "我还是拉丁字符/f/的小写", the sequence of the adjectives and nouns is in reverse order, and the right sequence should be "我还是小写的拉丁字符/f/".

## Screenshots

N/A

## Environment

It's in the simplified Chinese branch

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by amyjko** [comment]
No reply, unassigning @Siqi1234.

**Comment by amyjko** [comment]
No reply :( Unassigning @Siqi1234.

**Comment by twu29** [comment]
Hi Amy, @amyjko I'm interested in working on this issue. Could you assign it to me and provide me with some guidance please?

**Comment by amyjko** [comment]
Yay, thanks for helping clean up the locale!
