### ISSUE TITLE
Source file name doesn't change when switching languages in tutorial

### ISSUE THREAD

**Issue by ahuynh00** [wordplaydev/wordplay#420]
The source file named "Start" is located on the secondary bottom bar of Learn page (as with all projects).
It seems like if you have more than one language listed at the bottom right corner (next to the keyboard in the Learn window), **Start**  will be written in the very first language on that list, even if the current locale you are on is in a different language. Similarly, in the first 2 images, there are certain words in the palette options that remain in Chinese despite the current chosen language being different (English/ Spanish).

Below are examples of **Start** button being in a language other than the current chosen locale:
<img width="1497" alt="Yes And No" src="https://github.com/wordplaydev/wordplay/assets/91906524/6ba626fd-f5c5-496e-bb37-a953c6e9ac6b">
<img width="1512" alt="Scene 1" src="https://github.com/wordplaydev/wordplay/assets/91906524/7eb941a2-b5a2-4988-8f9b-1985b29626be">
<img width="1512" alt="Pasted Graphic 4" src="https://github.com/wordplaydev/wordplay/assets/91906524/3c1dc4c0-0721-49e0-8301-2dcdb985757e">

## Environment

Desktop

-   mac OS 14.0
-   Safari 17.0
-  Chrome 122.0.6261.111

**Comment by amyjko** [comment]
In this issue, `start` refers to name of the main source file for a project. When the project is created in `TutorialView`, it uses the locale's name for the start file, but only gives it that one name, and so if someone switches to a different language, it still has the original name given. 

I renamed this issue to reflect the root cause.

Here are some possible ways to make this clearer:

1. Don't show the name of the source files in the tutorial view because they aren't particularly helpful anyway, since we only ever have one source file in examples.
2. When switching to a new language while in the tutorial, add the new language's default source name to the source file's list of name aliases, so it appears in that new language as well.
3. When switching locales (in any project context, not just the tutorial), rearrange the project's source file names to match the order of the project's list of locales
4. Allow the project's locales to be reordered to match the selected locales, so the intended name appears

We might do all of these, or a combination of these, just to keep things consistent with selected locales, and avoid confusion like this.
