### ISSUE TITLE
Tutorial Typos

### ISSUE THREAD

**Issue by cdong03** [wordplaydev/wordplay#450]
## Expected behavior

We expect the tutorial's instructions and storyline to lack typos and grammatical errors.

## Actual behavior

When reading through the tutorial, there are typos and grammatical errors like comma splicing.

1. Go to the Wordplaypen website.
2. Click on "Learn".
3. In the top left, use the navigator to go to Program.
4. Use the arrows to navigate to 5/11.
5. Scroll down in the left-side window to see the typo, "... and put the result on on stage..."
6. Keep going through the tutorial to see more typos.

## Screenshots

<img width="254" alt="Screenshot 2024-04-24 180221" src="https://github.com/wordplaydev/wordplay/assets/91623204/d51a7c94-e807-4c15-8fb9-9607b4a7d3ed">
<img width="283" alt="Screenshot 2024-04-24 180317" src="https://github.com/wordplaydev/wordplay/assets/91623204/b3bc1dba-b667-4867-9494-ae6e18985852">
<img width="308" alt="Screenshot 2024-04-24 180421" src="https://github.com/wordplaydev/wordplay/assets/91623204/b6fa58d7-7265-42e8-9e09-1029aadc2e97">

## Environment

Laptop

-   OS + version: Windows 11
-   Browser + version: Chrome 124.0.6367.61

**Comment by cdong03** [comment]
@amyjko May I ask why this issue was closed? I was working on it, and there still seem to be errors.

**Comment by amyjko** [comment]
I assigned myself to the issue 2 days ago and resolved it this morning. The person assigned to the issue is the one responsible for fixing it; if you were working on it, you should have assigned yourself to the issue so I and others would know. There's no other way I could know you're working on it; this is how we coordinate our work.

If you have new typos that you're resolving, you can open a new issue and assign yourself to it so that everyone knows you're working on it. If you're working through the tutorial to find typos, consider opening a draft pull request to track that work, making commits every time you fix something, so everyone knows you're working on it.

**Comment by cdong03** [comment]
Thanks, I understand; I'll make a new issue.

**Comment by amyjko** [comment]
Sounds good! Sorry about the process confusion; think of GitHub as the ground truth: everything happening needs to be visible here.

**Comment by amyjko** [comment]
Oh, and a draft Pull Request is definitely a better format for a bunch of typo fixes. You're welcome to submit one of those instead, if it's going to be a bunch of straightforward commits for fixing typos.
