### ISSUE TITLE
Mitigating tab crashes from the program trying to run too many instructions

### ISSUE THREAD

**Issue by minkere** [wordplaydev/wordplay#489]
## What's the problem?

Too many instructions, including ones from very simple functions such as `'hello'.repeat(5000000)` can cause the page to freeze from attempting to run a large amount of instructions in a small span of time. Because the instructions are run as soon as the page loads, this means every attempt to reopen the project will cause the page to freeze and make the project inaccessible to the user.

## What's the design idea?

The design idea is to develop a solution that can try to mitigate the cases in which an individual could have too many instructions run and lead to a page freeze, but there are many ways in which this idea can be implemented. One concept could be to restrict the amount of instructions a user can write to preemptively prevent freezes.

Another could be to have all projects start inactive and have the user manually run the program in order to have the instructions read. 

I believe that the potential solution should retain the interactivity that comes from being able to instantly see the results of the code that you type in in some way.

**Comment by amyjko** [comment]
Triaging this one, I learned a few things:

* Since `Text.repeat` is a built-in function, it isn't subject to the instruction count limit
* The crash isn't caused by evaluation time, but rather render time in the browser for very large strings. The appropriate fix here is just limiting the length of rendered text in `TextView`.
* `TextView` already truncates long strings, but doesn't in some cases.

I'm going to push a change that properly truncates long text in all cases.
