### ISSUE TITLE
(Possibly?) Multiple Textbox Wrapping Onto Each Other From Dragging 

### ISSUE THREAD

**Issue by joonpiter** [wordplaydev/wordplay#496]
## Expected behavior
Possible dragging of function (possibly) causing wrapping and making them go into each other 

## Actual behavior

Shouldn't drag into each other(?)

## Screenshots
![IMG_2460](https://github.com/wordplaydev/wordplay/assets/75423505/fc93ad05-0cf7-4569-bcb0-1f5d9cdc6efb)

## Environment
Windows 11 on Chrome browser (ischool computer in Mary Gates)

**Comment by thesmolcoder** [comment]
We have found that this occurs when on the mouse setting instead of a keyboard. It was not noticed that this setting was selected at the time. 


<img width="510" alt="Screenshot 2024-06-26 at 2 09 23 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/eb88506d-a0fe-4251-9916-d564cf198803">
<img width="510" alt="Screenshot 2024-06-26 at 2 09 23 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/eb88506d-a0fe-4251-9916-d564cf198803">

**Comment by amyjko** [comment]
It sounds like this happened due to copy and paste, and that deleting didn't work well, nor did dragging it out.

**Comment by amyjko** [comment]
Closed in favor of #529. Conversation about the redesign will go there.
