### ISSUE TITLE
Operators in wordplay require spaces between them

### ISSUE THREAD

**Issue by emansuw** [wordplaydev/wordplay#520]
### What happened?

In wordplay when I create a project that does some addition like 2+2 it requires that there is a space between the number and operator. So it needs to be 2 + 2. 

### Anything else?

Not sure if this is an actual bug. If it isn't I would appreciate a better error message that says something like "Not parsable needs space between operator and number"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by amyjko** [comment]
This is not a bug; it's a tradeoff in the syntax of the language to allow for infix operators while also allowing unary operations like `+`, `-`. The space is what distinguishes unary from binary operations. But a better error message is definitely a good idea, since this whitespace sensitivity is obscure.

**Comment by amyjko** [comment]
I resolved this with a few things:

* I updated the parser to parse both `1 - 1`, `1-1`, and `1- 1` as a binary evaluation. The only one that doesn't is `1 -1`, which is interpreted as `1` and then the unary expression `-1`. 
* When there is a space after the left side and not on the right, then there will be a conflict resolution offered to add a space if adding the space would be valid.

Hopefully this resolves lots of the error prone cases!
